### ISSUE TITLE
Filter acf_color_palette doesn't appear to work / Styles Missing

### ISSUE THREAD

**Issue by 2gen** [Log1x/modern-acf-options#1]
Hi @Log1x,

Trying to use this package however it appears different then your screen shot - the styling seems wonky. The acf_color_palette filter doesn't seem to apply any changes either.

I see this repo. is ~4 years old, I'm guessing the changes to ACF and WordPress have rendered this package obsolete?

Thanks.

**Comment by Log1x** [comment]
hey. this is super old but i still use it without any issues. 😂 

can you share a screenshot or check console to make sure the stylesheet is loading? are you using Tabs like the README example?

**Comment by 2gen** [comment]
I've just copied the sample from the readme, including all three Customization options (and changed the colors). It's rendering like this:

![image](https://github.com/user-attachments/assets/8797f8d4-14c9-4754-9b83-c62145c279b8)

If the style sheet is missing I am not sure why. This is a default bedrock/sage/tailwind install.

~I see the plugin within the mu-plugin list within the WordPress dashboard.~ Sorry got your Modern Login plugin confused with this one.

**Comment by 2gen** [comment]
Sorry Log1x, I figured it out.

I included this package at the theme level and not the root bedrock level. Once included correctly I see the proper styling.

Thanks!

**Comment by Log1x** [comment]
Glad you got it sorted!
